networks:
  spark:
    external: true

services:
  csm-streaming-api:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        BUILD_DATE: ${BUILD_VERSION}
        HUGGINGFACE_TOKEN: ${HUGGINGFACE_TOKEN}
    container_name: csm-streaming-api
    environment:
      - INTERNAL_PORT=${INTERNAL_PORT}
      - CSM_API_KEY= ${CSM_API_KEY}
    volumes:
      - "${VOLUME_MAIN}:/csm-streaming-api"
    networks:
      - spark
    ports:
      - "${EXTERNAL_PORT}:${INTERNAL_PORT}"
    runtime: nvidia
    security_opt:
      - "label=type:nvidia_container_t"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: ['0']
              capabilities: [gpu, video]