networks:
  spark:
    external: false

services:
  csm-streaming-api:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        BUILD_DATE: ${BUILD_VERSION}
        HUGGINGFACE_TOKEN: ${HUGGINGFACE_TOKEN}
    container_name: csm-streaming-api
    stdin_open: true
    tty: true
    environment:
      - API_INTERNAL_PORT= ${API_INTERNAL_PORT}
      - DEMO_INTERNAL_PORT= ${DEMO_INTERNAL_PORT}
      - NO_TORCH_COMPILE= ${NO_TORCH_COMPILE}
      - CSM_API_KEY= ${CSM_API_KEY}
    volumes:
      - "/mnt/docker/containers/csm-streaming-api/instance1:/app/csm-streaming-api"
    networks:
      - spark
    ports:
      - "${API_EXTERNAL_PORT}:${API_INTERNAL_PORT}"
      - "${DEMO_EXTERNAL_PORT}:${DEMO_INTERNAL_PORT}"
    runtime: nvidia
    security_opt:
      - "label=type:nvidia_container_t"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: ['0']
              capabilities: [gpu, video]